### ISSUE TITLE
Will recursive contextual lookups be supported?

### ISSUE THREAD

**Issue by ctrlcctrlv** [cmyr/fea-rs#1]
```fea
lookup a_lkup {
  sub a a' lookup a_lkup;
  sub a by b;
  sub b' lookup b_lkup b;
} a_lkup;

lookup b_lkup {
  sub b by c;
} b_lkup;

feature liga {
  lookup a_lkup;
} liga;
```

Which as I understand it, will step as such, returning last line:

```
a a a a a
a a a a b
a a a c b
a a b c b
a b b c b
a c b c b
```

This allows you to write _backwards-affecting_ lookups if you are very careful and studious about how you go about it.

Want to loop in @simoncozens.

**Comment by cmyr** [comment]
I hadn't thought about this, but for me it comes down to what is allowed in the spec and what is supported by other tooling.

**Comment by ctrlcctrlv** [comment]
Recursion is definitely _allowed_ in the spec. Whether or not it is _honored_ is up to the shaper. It doesn't cause any font to fail for me under any shaper, but it's not honored by DirectWrite. This is very similar to the problem we have with OT LookupType 2 with an empty replacement being misunderstood/dropped/causing various bugs in shapers, except I'd figure more widespread.

It's a part of the spec that is easy to not think about so people didn't.

**Comment by simoncozens** [comment]
I don't think it's the feature compiler's job to police this. You should build lookups which do what the programmer asked you to do.

**Comment by ctrlcctrlv** [comment]
@simoncozens I certainly agree, but if recursion isn't considered while writing the compiler it might not work. Given Colin didn't know this could happen, I'm glad I mentioned it. I only recently figured it out myself.

**Comment by simoncozens** [comment]
It's fine. During the compiler all you're doing is a building a chaining lookup which refers to a lookup ID. You look up the name "a_lkup" in your list of named lookups, and get the lookup ID. Then you put it into the structure you've built. Who cares whether it's the ID of the current lookup or not? The *compiler* doesn't need to recursive into anything.

**Comment by ctrlcctrlv** [comment]
Isn't this compiler supposed to be fancier than a typical one? All kinds of syntax highlighting, modified bail outs, continuing to try to build files with errors? I do wonder if at least one of those things won't be affected.

**Comment by ctrlcctrlv** [comment]
Okay, so let's treat the issue as advisory, with nothing to fix, I'll close it. :-)
