### ISSUE TITLE
In-memory as a first class citizen

### ISSUE THREAD

**Issue by rsheeter** [cmyr/fea-rs#115]
`Source::from_text` says it's useful for testing. Source is very specifically defined as `A single source file, corresponding to a file on disk.` However, iiuc it's entirely reasonable to want to compile in memory. For example, having aggregated snippets from a .glyphs file why should I write them to the filesystem?

In attempting to actually do in-memory compile I ended up with:

```rust
    fn compile_memory(&self, fea_content: &String, glyph_order: GlyphMap) -> Result<FontBuilder, Error> {
        let source = Source::from_text(fea_content.clone());
        let (ast_root, diagnostics, includes) = parse_src(&source, Some(&glyph_order));

        if !includes.is_empty() {
            // TODO: print them. Right now IncludeStatement is opaque and lacks debug or display.
            return Err(Error::FeaError(format!("Impossible to resolve {} includes", includes.len())));
        }        
        let parse: ParseTree;  // I have a root, let me have a ParseTree
        self.compile_parse(parse)
    }
```

`compile_parse` was meant to be shared between memory and file compilation but I apparently can hold onto a ParseContext, such as from https://docs.rs/fea-rs/0.1.0/fea_rs/fn.parse_root_file.html, but not declare a function that takes one as a param.

**Comment by rsheeter** [comment]
Bonus points for not making me walk through quite so many of the intermediary steps, I just want to give you the source and glyph order and get the result.

```rust
pub struct CompileSuccess {
    compilation: Compilation,
    warnings: Vec<Diagnostic>,
}

pub struct CompileFailure {
    errors: Vec<Diagnostic>,
    warnings: Vec<Diagnostic>,
}

pub fn compile(source: &Source, glyph_map: Option<&GlyphMap>) -> Result<CompileSuccess, CompileFailure> {
    todo!("do the actual work!")
}
```

**Comment by rsheeter** [comment]
For reference, https://github.com/rsheeter/fea-rs/pull/1 shows what I did to unblock myself locally.

**Comment by cmyr** [comment]
Agree, I'm going to work on this API today and then I'll do a new release.
