### ISSUE TITLE
Handle magic comment for inserting generated kern info?

### ISSUE THREAD

**Issue by cmyr** [cmyr/fea-rs#205]
It's actually not clear to me if this should end up being our responsibility or not; it could also be up to the compiler, which could either concatenate the fea before sending it to us, or could replace the magic comment with an include statement.

cc @rsheeter is this a thing we need to be handling?

**Comment by anthrotype** [comment]
> up to the compiler

yeah, I think fea-rs should not handle these directly given they are not standard, but whomever calls fea-rs should pre-process these
