### ISSUE TITLE
Tell me how to provide the glyph order

### ISSUE THREAD

**Issue by rsheeter** [cmyr/fea-rs#230]
In trying to pin down steps to dig into https://github.com/googlefonts/fontc/issues/456 I got this error:

```shell
$ cargo run --features cli ../fontc/build/debug/features.fea 
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/fea-rs ../fontc/build/debug/features.fea`
No glyph order provided
```

I wish it had told me how to actually provide the glyph order.  If I run `cargo run --features cli --help` I don't see an obvious way to provide a glyph order.

**Comment by cmyr** [comment]
(resolved; you need to do use `--` to pass arguments to the final target of `cargo run`)
