### ISSUE TITLE
"sub X by NULL" is (sadly) acceptable

### ISSUE THREAD

**Issue by simoncozens** [cmyr/fea-rs#246]
There's a terrible hack that's not in the FEA specification, but is used by a number of fonts. It's possible to use multiple substitution to [delete a glyph](https://bugzilla.mozilla.org/show_bug.cgi?id=1128658); this is supported by [the spec](https://github.com/adobe-type-tools/afdko/pull/1294), in fonttools and makeotf.

Because you can do `sub X by NULL` you can also do `sub a X' by NULL;` but currently fea-rs pulls a face at this:

```
error: Expected glyph class features.fea at 4004:22
     |
4004 | sub @All.Medis r0' by NULL;
```

**Comment by cmyr** [comment]
okay I think this is just an oversight in the parsing of contextual lookups, we do support the `sub X by NULL` syntax in non-contextual... contexts. Will take a look. :)

**Comment by cmyr** [comment]
I guess this means we should also support,

```fea
sub @someclass a';
```
to be an implied `by NULL`?

**Comment by simoncozens** [comment]
I don't think we need an implied one, no - the syntax for deleting is `sub <single glyph> by NULL`, nothing else. But we need both `x by NULL;` and `<context> x' <context> by NULL;`

**Comment by cmyr** [comment]
I was just thinking of how in various places the spec says, "Omitting the by clause is equivalent to adding `by NULL`".

**Comment by cmyr** [comment]
oh also: this repo has moved into `fontc`, I'll see about moving this issue over there.

**Comment by simoncozens** [comment]
Maybe archive it, then?
