### ISSUE TITLE
Table packing / overflow resolution

### ISSUE THREAD

**Issue by simoncozens** [cmyr/fea-rs#3]
This is basically an FYI in case you haven't seen it; I know you don't need it yet, but I just wanted to dump this information somewhere you can refer to it when it's time to.

Behdad outlines a couple of strategies for better overflow resolution in [this thread](https://github.com/fonttools/fonttools/issues/1105); at the end I just updated the 99proof branch of fontools, but it still breaks on overflow.

In fonttools-rs, the building of the object graph and resolving of offsets is localised to [this file](https://github.com/simoncozens/fonttools-rs/blob/main/crates/otspec/src/offsetmanager.rs) which builds an acyclic graph and orders it but currently makes no attempt to check for overflow. So it should be possible to improve the Rust implementation just by hacking on that one file.

Similarly in Harfbuzz, the object packing is handled in [hb-repacker.hh](https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-repacker.hh) but notice that when something does overflow there are a lot of TODOs and not a lot of actual resolution.

**Comment by cmyr** [comment]
Yea, this is definitely the scariest bit of this project. There's [another related document](https://github.com/googlefonts/googlefonts.github.io/blob/main/harfbuzz_overflow_resolution.md) here.

**Comment by simoncozens** [comment]
In the worst case, the existing fontTools implementation *works*, it’s just suboptimal and slow. But it’s only slow because Python. So a straight port is a possibility.

**Comment by cmyr** [comment]
I've ported the harfbuzz packing algorithm, including extension promotion and initial work on table splitting (currently just pair pos format 1) so I'm going to close this in favour of finer-grained issues.
